In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
# Q1
np.__version__

'1.21.6'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-07 15:17:09--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.05s   

2022-09-07 15:17:09 (25.7 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [4]:
# Q2
df = pd.read_csv('data.csv')
len(df)

11914

In [22]:
df.head(2)

make       model  year             engine_fuel_type  engine_hp  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650

In [6]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [23]:
df.head(2)

make       model  year             engine_fuel_type  engine_hp  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650

In [24]:
# Q3
df.make.value_counts()[:3].index

Index(['Chevrolet', 'Ford', 'Volkswagen'], dtype='object')

In [9]:
# Q4
df[df.make == 'Audi'].model.nunique()

34

In [14]:
# Q5
sum(df.isnull().sum() != 0)

5

In [15]:
# Q6
print(df.engine_cylinders.median())
most_freq = df.engine_cylinders.describe()['max']
en_cil_wo_na = df.engine_cylinders.fillna(most_freq)
print(en_cil_wo_na.median())

6.0
6.0


In [26]:
# Q7
X = df[df.make == 'Lotus'][['engine_hp','engine_cylinders']].drop_duplicates().values
print(X)
XTX = X.T.dot(X)
print(XTX)
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
print(XTX_inv.dot(XTX).round())
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
w = XTX_inv.dot(X.T).dot(y)
w[0]


[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]
[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]
[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]
[[ 1. -0.]
 [ 0.  1.]]


4.594944810094551